### ISSUE TITLE
SCIL Hackathon

### ISSUE THREAD

**Issue by AlexVCaron** [scilus/nf-scil#59]
Get your job here ! https://docs.google.com/spreadsheets/d/1lsXqGz85tGZ_Bf6WpOFKbe7erzOKBvF2fQNzTkqHZoI/edit#gid=1691213137

**Comment by AlexVCaron** [comment]
PR workflow : fix pytest-changes job, paths-filter ref to previous commit, should ref to previous valid build in PR

**Comment by AlexVCaron** [comment]
Add documentation on inputs/outputs types for meta.yml

**Comment by karanphil** [comment]
Scripts using --not_all can crash if none of the output files are given.
