### ISSUE TITLE
Fodf metrics should be a module

### ISSUE THREAD

**Issue by karanphil** [scilus/nf-scil#64]
I think `scil_compute_fodf_metrics.py` should be in a module in itself, and not inside the `fodf` module. The reason is, it would be nice to have a `ssstfodf` and a `msmtfodf` (damn no _!) module. A module `fodfmetrics`, just like the `dtimetrics`, would take as input any SH file.

**Comment by AlexVCaron** [comment]
Hi @karanphil ! I had a thought about this, and I think in the end we should sought something akin to what you propose. I really like the idea of having `ssstfodf` and m̀smtfodf` as separate modules (and eventually `memsmt`!), it works with the logic of `nf-scil`, makes the modules interface a bit clearer and trying to bunch both in the same module could create a really ugly script.

However, as discussed, the metric script call will stay inside those modules. Its going to create duplication, but we'll handle this in future iterations. You can however still propose a module doing only metrics computation, for both DTI and SH, I am all good with that !
