### ISSUE TITLE
scilpy 2.0

### ISSUE THREAD

**Issue by AlexVCaron** [scilus/nf-scil#79]
We'll have to adapt all modules when Scilpy v2.0 releases. There will be renaming to do and validation on input parameters. We will also enable the review and merge of a bunch of Hackathon PRs.

Solved once scilus/scilpy#917 is closed

**Comment by AlexVCaron** [comment]
- [ ] #132 
- [ ] #134

**Comment by gagnonanthony** [comment]
Remaining modules to migrate to scilpy 2.0.0:

- `reconst` : I already started, so I'll take it!
- `register` + `registration`
- `segmentation`
- `tracking`

@AlexVCaron @arnaudbore @ThoumyreStanislas @Manonedde
